name: Plugin Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get required PHP version
        id: php_version
        run: |
          PHP_VERSION=$(grep "Requires PHP:" stop-user-enumeration/stop-user-enumeration.php | awk '{print $3}')
          echo "PHP_VERSION=$PHP_VERSION" >> $GITHUB_OUTPUT
          echo "Plugin requires PHP $PHP_VERSION"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ steps.php_version.outputs.PHP_VERSION }}
          coverage: none
          tools: composer, wp-cli

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpcs checks
        run: composer run-script check

      - name: Install WP-CLI dist-archive command
        run: wp package install wp-cli/dist-archive-command:@stable

      - name: Build plugin
        run: |
          cd stop-user-enumeration && composer install --no-dev && cd ..
          wp dist-archive ./stop-user-enumeration ./stop-user-enumeration.zip
          mkdir tmp-build
          unzip stop-user-enumeration.zip -d tmp-build

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: './tmp-build/stop-user-enumeration'
