name: Plugin Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, wp-cli

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpcs checks
        run: composer run-script check

      - name: Install WP-CLI dist-archive command
        run: wp package install wp-cli/dist-archive-command:@stable

      - name: Build plugin
        run: |
          cd stop-user-enumeration && composer install --no-dev && cd ..
          wp dist-archive stop-user-enumeration ./stop-user-enumeration.zip
          mkdir tmp-build
          unzip stop-user-enumeration.zip -d tmp-build

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: './tmp-build/stop-user-enumeration'
